version: '3.8'
services:
    postgres-environment:
        container_name: postgres-server
        image: ghcr.io/mateuscavalc/postgres-server:main # Imagem do github repository
        restart: always
        ports:
            - 5432
    python-environment:
        container_name: python-server
        image: ghcr.io/mateuscavalc/python-server:main # Imagem do github repository
        depends_on:
            - postgres-environment
        restart: always
        ports:
            - "9090:9090"
        links:
            -  postgres-environment:postgres_server